from app.models._base import Base, MetadataMixin, TimestampMixin
from app.models.academics import (
    Department,
    Faculty,
    HodProfile,
    IndustryPartner,
    Laboratory,
    StudentAward,
    StudentProject,
)
from app.models.admissions import (
    AdmissionCounsellor,
    AdmissionFAQ,
    AdmissionLead,
    AdmissionStep,
    AdmissionTimeline,
    ContactSubmission,
    FeeComponent,
    JobApplication,
    JrfPosting,
    OpenPosition,
    Quota,
    RequiredDocument,
)
from app.models.cms import NavItem, NavMenu, Page, PageSection
from app.models.compliance import (
    AlumniChapter,
    AlumniMentorship,
    AlumniProfile,
    BoardMember,
    CommitteeMember,
    NaacDocument,
    NaacGrade,
    NirfRecord,
    Official,
)
from app.models.content import MediaAsset, Setting
from app.models.events import (
    Announcement,
    ClubCell,
    Event,
    GalleryCategory,
    GalleryItem,
    Notice,
    Video,
)
from app.models.posts import Post
from app.models.placements import (
    MoU,
    PlacementRecord,
    PlacementStatistic,
    Recruiter,
    RecruiterCategory,
    RecruiterTestimonial,
    TapEvent,
    TapService,
    TapTeamMember,
)
from app.models.research import (
    BookOrChapter,
    Conference,
    ConferencePaper,
    Fdp,
    FdpSession,
    JournalIssue,
    Patent,
    PolicyDocument,
    Publication,
    ResearchFocusArea,
)
from app.models.scope_preset import ScopePreset
from app.models.user import AuditLog, LoginAttempt, RefreshToken, Scope, User, UserScope

__all__ = [
    "AdmissionCounsellor",
    "AdmissionFAQ",
    "AdmissionLead",
    "AdmissionStep",
    "AdmissionTimeline",
    "AlumniChapter",
    "AlumniMentorship",
    "AlumniProfile",
    "Announcement",
    "AuditLog",
    "Base",
    "BoardMember",
    "BookOrChapter",
    "ClubCell",
    "CommitteeMember",
    "Conference",
    "ConferencePaper",
    "ContactSubmission",
    "Department",
    "Event",
    "Faculty",
    "Fdp",
    "FdpSession",
    "FeeComponent",
    "GalleryCategory",
    "GalleryItem",
    "HodProfile",
    "IndustryPartner",
    "JobApplication",
    "JournalIssue",
    "JrfPosting",
    "Laboratory",
    "LoginAttempt",
    "MediaAsset",
    "MetadataMixin",
    "MoU",
    "NaacDocument",
    "NaacGrade",
    "NavItem",
    "NavMenu",
    "NirfRecord",
    "Notice",
    "Official",
    "OpenPosition",
    "Page",
    "PageSection",
    "Patent",
    "PlacementRecord",
    "PlacementStatistic",
    "PolicyDocument",
    "Post",
    "Publication",
    "Quota",
    "Recruiter",
    "RecruiterCategory",
    "RecruiterTestimonial",
    "RefreshToken",
    "RequiredDocument",
    "ResearchFocusArea",
    "Scope",
    "ScopePreset",
    "Setting",
    "StudentAward",
    "StudentProject",
    "TapEvent",
    "TapService",
    "TapTeamMember",
    "TimestampMixin",
    "User",
    "UserScope",
    "Video",
]
